# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheproduit',
            name='prix',
            field=models.DecimalField(decimal_places=10, default=50, max_digits=19),
            preserve_default=False,
        ),
    ]
