# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_ficheproduit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheproduit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'media/product'),
        ),
        migrations.AlterField(
            model_name='ficheproduit',
            name='prix',
            field=models.DecimalField(decimal_places=9, max_digits=19),
        ),
    ]
