# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_auto_20171113_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheproduit',
            name='enStock',
        ),
        migrations.AddField(
            model_name='ficheproduit',
            name='stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficheproduit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
