# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('adresse1', models.CharField(max_length=100)),
                ('adresse2', models.CharField(max_length=100)),
            ],
        ),
    ]
