# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='codePostal',
            field=models.CharField(default='49000', max_length=5),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='ville',
            field=models.CharField(default='Angers', max_length=80),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
